### ISSUE TITLE
關於幼兒園裁罰

### ISSUE THREAD

**Issue by zxcasdqwevfrbgth** [kiang/preschools#11]
江先生您好，敝園被裁罰的紀錄之前已被教育局撤銷掉，請問如何連繫您協助回收過時資訊，多謝。

**Comment by kiang** [comment]
如果只是因為公告時間截止而撤下，基本上不會移除；如果確認是違規事實認定錯誤請直接上傳撤銷裁罰記錄的公文書，感謝
