### ISSUE TITLE
光大幼兒園無資訊與價格

### ISSUE THREAD

**Issue by Cowknowfish** [kiang/preschools#5]
中市大雅區雅環路1段300巷1弄的光大幼兒園無資料與每月價格

**Comment by kiang** [comment]
看起來是雅環路一段332巷1號這個？
https://kiang.github.io/preschools/#95ca2a90-6e25-4a2e-9dca-e219ad24af29

**Comment by Cowknowfish** [comment]
對耶，怎麼跑到那裡去，位置完全不對😅

**Comment by kiang** [comment]
Google 地圖標示的位置正確嗎？如果正確我就比照修正
https://goo.gl/maps/kCGF4iufXzL8qo1e7

**Comment by Cowknowfish** [comment]
是正確的喔，我之前每星期假日都有帶女兒到那邊散步。

**Comment by kiang** [comment]
好的，應該已經修正了

**Comment by Cowknowfish** [comment]
有看到修正了喔，謝謝您🙏
