### ISSUE TITLE
跟著三角形的數字是該幼兒園的最低每月收費，個別幼兒園可能因為年齡不同而有不同的收費

### ISSUE THREAD

**Issue by NijopWu** [kiang/preschools#7]
臺南市私立愛兒堡幼兒園，最低收費標準為3~5歲，全學期總收費49,082+課後延托費2,200/月，
故三角形數字應為49,082÷6 + 2,200 = 10,380.33
但網站顯示數字為$5,700元/月
(即使課後延托費不計，49,082÷6 = 8,180.3/月)

以上情況不限這間，可能麻煩要查一下資料庫的算式。

**Comment by kiang** [comment]
因為該幼兒園有加入準公共化，所以收費的計算會以政策補助後金額顯示

準公共化目前政策是每月收費 3500 + 課後延托費 + 家長會費

**Comment by NijopWu** [comment]
如果這樣的話，那公立的也應按照政策補助後金額(每月最高不超過1,000)顯示，
如否，則於說明處更清楚詳述？
(例如：公私立以原始金額、準公共以政策補助後金額顯示...etc)

另外建議是否全數按「全學期總收費/月數」呈現？
畢竟額外的費用，並非一致性的，縱然有課後延托費，
但我未必會參加課後延托(交通費亦是，另外也不是每間都成立家長會)
在資料的顯示上卻有列入，造成看此幼兒園月費很高，結果是被延托費(或交通費、家長會費)虛增，
對於三角形月費的參考價值，變成還要再點進去確認。

或是明宗大認為有一定要列入的理由，那看能否再多寫個功能，
三角形月費可以選取是否包含(延托費、交通費、家長會費)這樣？

**Comment by kiang** [comment]
目前的邏輯
1. 如果是準公共化，費用 3500 + (課後延托費 + 家長會費) / 月份數
2. 如果有列舉 "全學期總收費" ，會直接以該欄位數字除以月份數+ (課後延托費 + 家長會費) / 月份數，私立一般都是 6 個月，公立則是有 4.6~4.7 不等的數字
3. 如果上述都不是就會加總 學費+雜費+材料費+活動費+午餐費+點心費+課後延托費+家長會費 然後除以月份數

基本上試算出來的月收費只是一個參考，因為我沒辦法清楚每個縣市是否有延伸自訂的作法，稍後會把上述公式補充到說明中
