### ISSUE TITLE
裁罰記錄的內容是空的

### ISSUE THREAD

**Issue by RosaShao** [kiang/preschools#8]
![Screenshot_20230610-105328](https://github.com/kiang/preschools/assets/40678129/d566a35b-7e51-44b5-8f9d-3db30be8a69a)
如截圖所示，裁罰內容是空的，感謝您的付出！

**Comment by kiang** [comment]
感謝回報，可能是市府一次匯入較多資料沒處理到，手動更新後已經可以看到

![Screenshot from 2023-06-13 11-48-38](https://github.com/kiang/preschools/assets/47844/27ccf7d3-fd23-4c99-a327-5dc8fcc09a23)
